project:
  type: website
  resources:
    - CNAME
  output-dir: docs

website:
  title: "Raffaele Danna"
  site-url: "https://rafdanna.com"
  favicon: /files/my-favicon.png
  navbar:
    left:
      - href: Publications.qmd
        text: Publications
      - href: Projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV

format:
  html:
    toc: false
    theme:
      light: cosmo
      dark: darkly
    respect-user-color-scheme: true
    css: styles.css
    includes:
      in-header: |
        <link rel="canonical" href="{{< meta site-url >}}{{< meta page-url >}}">

editor: visual